apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: mon-application
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nginx-web
  ports:
    - port: 80
      targetPort: 8080
      nodePort: {{ .Values.service.nodePort }}
