apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: mon-application
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: {{ .Values.service.nodePort }}
